### ISSUE TITLE
Intial Architecture Diagrams

### ISSUE THREAD

**Issue by Pol-Lanski** [dappnode/liquidity-mining-v2#7]
We need an initial understanding of how would the pieces of the Liquidity Mining v2 program would work.

For reference, look at https://github.com/dappnode/liquidity-mining-v2/issues/2 and its comments.

**Comment by DAppDanil** [comment]
Here's the scheme we drew on multiple calls while discussing the structure:

https://excalidraw.com/#room=965376334a69311c37bb,Ivqc_J5u7yeRgFGV62C4bQ
